vich_uploader:
    db_driver: orm
    mappings:
        fishes:
            uri_prefix: /images/fishes
            upload_destination: '%kernel.project_dir%/public/images/fishes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
